### ISSUE TITLE
Powershell script to manupulate Solutions

### ISSUE THREAD

**Issue by IndDan** [seanmcne/Microsoft.Xrm.Data.PowerShell.Samples#17]
Are there any scripts to increase Solution version number using Powershell ?
Any pointer to some of these scripts will be helpful.

Dan.

**Comment by seanmcne** [comment]
@IndDan - absolutely, use get-crmrecords to pull in the solution records including the version number.  You can then use the VersionNumber class (or string parsing) to read the version # and increment it.  I've done this in the past but don't have a great script to paste in - but focus in on the logic of parsing the version# and how you want to increment it.  Wiring that up to read then write to the CRM solution will be trivial once you have that. 

Thanks!

**Comment by IndDan** [comment]
Thank you Sean. We used Get-CrmSolutionVersion using Adxstudio powershell module. I will try with the method you described.

**Comment by seanmcne** [comment]
Here's a quick sample of pulling in all CRM solutions in your environment and adding a SolutionVersion property to the CrmRecord - this will be a System.Version and gives you the ability to get the minor version as an int and calling ++ or something like that.  Then you can just update your solution, since crm uses a text version # you'll probably want to have it in a System.Version object so you can compare it without having to parse it yourself.  One drawback is you need to create a new version object to store increments or create a string as in the example below. 

You can then tweak this, add a function to increment the major or minor, or use a function to parse and increment, etc.  

I hope this helps get you something to start with.  If you had an example of the adx function and what it did we could do something similar here if it was helpful. 

``` powershell
function minZero($value){
	return (&{If($value -lt 0) {0} Else {$value}})
}

$solutions = Get-CrmRecords -EntityLogicalName solution -Fields version,friendlyname,uniquename,description 

$solutions.CrmRecords|foreach{
     Add-Member -InputObject $_ -NotePropertyName "SolutionVersion" -NotePropertyValue ([System.Version]($_.version))
}

$versionString = "$(minZero($rv1.Major)).$(minZero($rv1.Minor)).$(minZero($rv1.Build)).$(minZero($rv1.Revision))"

```

**Comment by IndDan** [comment]
Thank you So much Sean. Very much appreciate writing sample code.

**Comment by seanmcne** [comment]
No problem, glad I could assist!
