### ISSUE TITLE
Bulk Duplicate Deletion jobs using a script

### ISSUE THREAD

**Issue by venkatkrk** [seanmcne/Microsoft.Xrm.Data.PowerShell.Samples#3]
Any thoughts on how we could run a bulk duplicate deletion job using powershell with a predefined view. The idea is to export all duplicate contacts in a csv file, so it can be investigated further in a spreadsheet.

On a similar note, any thoughts on retrieving a multi-page view result from powershell. Get-CrmRecordsByViewName only returns the first 5000 results. It will be great to retrieve the entire result set 99,999

**Comment by kenakamu** [comment]
Firstly, Get-CrmRecordsByViewName has -AllRows option. Please use following command to see detail of each function.

``` powershell
Get-Help Get-CrmRecordsByViewName -Detailed
```

For Duplicate Detection, SDK has RetrieveDuplicatesRequest which you can retrieve duplicates by using name, so it is not possible to implement that, but we need to carefully think how we should do. So ideally, should the function looks like this?

Get-CrmDuplicateRecords -conn $conn -Fetch $fetch

The tricky part is how we know which attributes are enabled for duplicates. If we can identify as parameter for the function, that is easier though.

Get-CrmDuplicateRecords -conn $conn -Fetch $fetch -Field "name"

Then results set is another part we need to carefully consider. Maybe like this? For deleting we should keep each records id, too.
Record    DupRecords

---

Record1  Record2, Record3
Record2, Record1, Record3

Appreciate your opinion.

**Comment by venkatkrk** [comment]
My understanding of how CRM works today is, we first publish the duplication detection rules in CRM for the entity.

Then we run a duplicate detection job for that entity with a recordset defined by fetchxml (great to be able to use a view instead)
Once the duplicate detection job finishes, we need ability to download results of the detection job.

In summary, here would be the ideal command

GetCRMDuplicateRecords  -conn $conn -viewName  "view" -EntityLogicalName "entity" -OutputFile "file"

-Venkat

**Comment by seanmcne** [comment]
@venkatkrk I'm just going through some of the older issues logged and ran across this one.  The duplicate report should be accessible via the module.  Each duplicate detection job is essentially an asyncoperation / system job.  To find the dups of a job take the asyncoperationid of the job and run a query like this: 

```powershell 
Get-CrmRecords -EntityLogicalName duplicaterecord -FilterAttribute asyncoperationid -FilterOperator eq -FilterValue AC376131-2351-E711-8100-E0071B66CFA1 

```

now you'll have a collection of records that are duplicates, you'll have a 'baserecordid' and the duplicate it's matched to.  As for the best way to render this, your approach will probably be as good as any :)  the data is a bit complex due to the N:N nature so you'll probably have to pick a direction to render from - CRM just shows all baserecords in a grid then renders all duplicates for that base record below. Good luck!
